services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

    volumes:
      - redis-data:/data

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - prowlarr-config:/config

  torrserver:
    build: ./docker/torrserver-gst
    restart: unless-stopped
    volumes:
      - torrserver-data:/opt/ts
    devices:
      - /dev/dri:/dev/dri
    mem_limit: 5g
    ports:
      - "6881:6881"
      - "6881:6881/udp"

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info

  torresmin:
    build: .
    restart: unless-stopped
    depends_on:
      - redis
      - prowlarr
      - torrserver
    environment:
      - JACKETT_URL=http://prowlarr:9696
      - JACKETT_API_KEY=${JACKETT_API_KEY}
      - REDIS_URL=redis://redis:6379
      - CONFIG_DATA_DIR=/data
      - PORT=7860
      - ADDON_PUBLIC_URL=${ADDON_PUBLIC_URL}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - TS_URL=http://torrserver:8090
      - TS_USER=
      - TS_PASS=
    volumes:
      - torresmin-data:/data

volumes:
  redis-data:
  prowlarr-config:
  torrserver-data:
  torresmin-data:
